# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ad0-dtbZYN7duNJPxcmNlguVB5XTK920
"""

import streamlit as st
import PyPDF2
import docx
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
import google.generativeai as genai
import os

# --- CONFIG ---
st.set_page_config(page_title="Resume Formatter", layout="wide")
genai.configure(api_key=st.secrets["GEMINI_API_KEY"])

# --- SIDEBAR ---
st.sidebar.title("🏢 Branding")
company_choice = st.sidebar.selectbox("Select Company", ["Synectics", "W3G", "ProTouch"])
contact_number = st.sidebar.text_input("Contact Number", "123-456-7890")

# --- TEMPLATE PATHS ---
TEMPLATE_MAP = {
    "Synectics": "Synectics.dotx",
    "W3G": "W3G.dotx",
    "ProTouch": "ProTouch.dotx"
}

# --- HELPER: LOAD TEMPLATE ---
def load_template(company):
    path = TEMPLATE_MAP.get(company)
    if path and os.path.exists(path):
        return docx.Document(path)
    return docx.Document()

# --- HELPER: PARSE AI OUTPUT ---
def parse_resume(text):
    sections = {"SUMMARY": "", "SKILLS": [], "EXPERIENCE": [], "EDUCATION": []}
    current = None

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue

        upper = line.upper()

        if "SUMMARY" in upper:
            current = "SUMMARY"
            continue
        elif "SKILL" in upper:
            current = "SKILLS"
            continue
        elif "EXPERIENCE" in upper:
            current = "EXPERIENCE"
            continue
        elif "EDUCATION" in upper:
            current = "EDUCATION"
            continue

        if current == "SUMMARY":
            sections["SUMMARY"] += line + " "
        elif current == "SKILLS":
            sections["SKILLS"].append(line)
        elif current in ["EXPERIENCE", "EDUCATION"]:
            sections[current].append(line)

    return sections

# --- HELPER: ADD HEADER ---
def add_header(doc, text):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(12)

# --- HELPER: ADD EXPERIENCE ---
def add_experience(doc, lines):
    for line in lines:
        if "|" in line:
            parts = line.split("|")

            p = doc.add_paragraph()
            p.paragraph_format.tab_stops.add_tab_stop(Inches(6.5))

            run = p.add_run(parts[0].strip().upper())
            run.bold = True

            p.add_run("\t")

            run2 = p.add_run(parts[1].strip())
            run2.italic = True
        else:
            doc.add_paragraph(line)

# --- MAIN UI ---
st.title("📄 Resume Formatter")

if "content" not in st.session_state:
    st.session_state.content = ""

uploaded_file = st.file_uploader("Upload Resume PDF", type="pdf")

# --- GENERATE AI TEXT ---
if uploaded_file and st.button("Generate Draft"):
    with st.spinner("Processing..."):
        reader = PyPDF2.PdfReader(uploaded_file)
        raw_text = "".join([p.extract_text() for p in reader.pages])

        model = genai.GenerativeModel("gemini-2.5-flash")

        prompt = f"""
        Reformat resume into sections:
        SUMMARY, SKILLS, EXPERIENCE, EDUCATION

        RULES:
        - Keep clean structure
        - Use "Company | Dates"
        - Role on next line
        - Skills one per line

        TEXT:
        {raw_text}
        """

        response = model.generate_content(prompt)
        st.session_state.content = response.text

# --- EDIT WINDOW ---
if st.session_state.content:
    st.session_state.content = st.text_area("Edit Content", st.session_state.content, height=400)

    if st.button("Generate Final Resume"):
        data = parse_resume(st.session_state.content)

        doc = load_template(company_choice)

        # --- SUMMARY ---
        if data["SUMMARY"]:
            add_header(doc, "SUMMARY")
            doc.add_paragraph(data["SUMMARY"])

        # --- SKILLS ---
        if data["SKILLS"]:
            add_header(doc, "SKILLS")
            for skill in data["SKILLS"]:
                doc.add_paragraph(skill, style="List Bullet")

        # --- EXPERIENCE ---
        if data["EXPERIENCE"]:
            add_header(doc, "EXPERIENCE")
            add_experience(doc, data["EXPERIENCE"])

        # --- EDUCATION ---
        if data["EDUCATION"]:
            add_header(doc, "EDUCATION")
            add_experience(doc, data["EDUCATION"])

        # --- FOOTER ---
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.add_run(f"Contact: {contact_number}").bold = True

        # SAVE
        buffer = io.BytesIO()
        doc.save(buffer)

        st.download_button(
            "Download Resume",
            buffer.getvalue(),
            file_name=f"{company_choice}_Resume.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        )
